# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'domecattabs.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(864, 660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.step_tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.step_tabs.setGeometry(QtCore.QRect(0, 0, 861, 611))
        self.step_tabs.setObjectName("step_tabs")
        self.query_tab = QtWidgets.QWidget()
        self.query_tab.setObjectName("query_tab")
        self.layoutWidget = QtWidgets.QWidget(self.query_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(3, 30, 211, 481))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_data_source = QtWidgets.QLabel(self.layoutWidget)
        self.label_data_source.setObjectName("label_data_source")
        self.horizontalLayout_2.addWidget(self.label_data_source)
        self.comboSelectSource = QtWidgets.QComboBox(self.layoutWidget)
        self.comboSelectSource.setObjectName("comboSelectSource")
        self.horizontalLayout_2.addWidget(self.comboSelectSource)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_tables = QtWidgets.QLabel(self.layoutWidget)
        self.label_tables.setObjectName("label_tables")
        self.horizontalLayout_4.addWidget(self.label_tables)
        spacerItem = QtWidgets.QSpacerItem(188, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.listView = QtWidgets.QListView(self.layoutWidget)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tablesTree = QtWidgets.QTreeView(self.layoutWidget)
        self.tablesTree.setObjectName("tablesTree")
        self.verticalLayout.addWidget(self.tablesTree)
        self.layoutWidget1 = QtWidgets.QWidget(self.query_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(3, 0, 851, 28))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_s_desc = QtWidgets.QLabel(self.layoutWidget1)
        self.label_s_desc.setObjectName("label_s_desc")
        self.horizontalLayout.addWidget(self.label_s_desc)
        self.lE_desc_query = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lE_desc_query.setObjectName("lE_desc_query")
        self.horizontalLayout.addWidget(self.lE_desc_query)
        self.Button_searchq = QtWidgets.QPushButton(self.layoutWidget1)
        self.Button_searchq.setText("")
        self.Button_searchq.setObjectName("Button_searchq")
        self.horizontalLayout.addWidget(self.Button_searchq)
        self.Button_prevq = QtWidgets.QPushButton(self.layoutWidget1)
        self.Button_prevq.setText("")
        self.Button_prevq.setObjectName("Button_prevq")
        self.horizontalLayout.addWidget(self.Button_prevq)
        self.lE_keyq = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lE_keyq.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lE_keyq.setObjectName("lE_keyq")
        self.horizontalLayout.addWidget(self.lE_keyq)
        self.Button_nextq = QtWidgets.QPushButton(self.layoutWidget1)
        self.Button_nextq.setText("")
        self.Button_nextq.setObjectName("Button_nextq")
        self.horizontalLayout.addWidget(self.Button_nextq)
        self.Button_delq = QtWidgets.QPushButton(self.layoutWidget1)
        self.Button_delq.setText("")
        self.Button_delq.setObjectName("Button_delq")
        self.horizontalLayout.addWidget(self.Button_delq)
        self.layoutWidget2 = QtWidgets.QWidget(self.query_tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(221, 30, 631, 481))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.comboBox_templates = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_templates.setObjectName("comboBox_templates")
        self.horizontalLayout_5.addWidget(self.comboBox_templates)
        spacerItem2 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.label_conditions = QtWidgets.QLabel(self.layoutWidget2)
        self.label_conditions.setObjectName("label_conditions")
        self.horizontalLayout_5.addWidget(self.label_conditions)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.scrollConditions = QtWidgets.QScrollArea(self.layoutWidget2)
        self.scrollConditions.setWidgetResizable(True)
        self.scrollConditions.setObjectName("scrollConditions")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 627, 74))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollConditions.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollConditions)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.Button_add_cond = QtWidgets.QPushButton(self.layoutWidget2)
        self.Button_add_cond.setObjectName("Button_add_cond")
        self.horizontalLayout_9.addWidget(self.Button_add_cond)
        spacerItem4 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox.setEditable(True)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_7.addWidget(self.comboBox)
        self.cmb_cross_ops = QtWidgets.QComboBox(self.layoutWidget2)
        self.cmb_cross_ops.setMinimumSize(QtCore.QSize(50, 0))
        self.cmb_cross_ops.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cmb_cross_ops.setObjectName("cmb_cross_ops")
        self.cmb_cross_ops.addItem("")
        self.cmb_cross_ops.addItem("")
        self.cmb_cross_ops.addItem("")
        self.cmb_cross_ops.addItem("")
        self.horizontalLayout_7.addWidget(self.cmb_cross_ops)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_7.addWidget(self.comboBox_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.scroll_across = QtWidgets.QScrollArea(self.layoutWidget2)
        self.scroll_across.setWidgetResizable(True)
        self.scroll_across.setObjectName("scroll_across")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 627, 73))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scroll_across.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.scroll_across)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ButtonADQL = QtWidgets.QPushButton(self.layoutWidget2)
        self.ButtonADQL.setToolTip("")
        self.ButtonADQL.setToolTipDuration(-1)
        self.ButtonADQL.setWhatsThis("")
        self.ButtonADQL.setObjectName("ButtonADQL")
        self.horizontalLayout_6.addWidget(self.ButtonADQL)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_6.addWidget(self.label_19)
        self.lE_filepath_ad = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lE_filepath_ad.setObjectName("lE_filepath_ad")
        self.horizontalLayout_6.addWidget(self.lE_filepath_ad)
        self.cmb_filetype_aq = QtWidgets.QComboBox(self.layoutWidget2)
        self.cmb_filetype_aq.setObjectName("cmb_filetype_aq")
        self.horizontalLayout_6.addWidget(self.cmb_filetype_aq)
        self.Button_submit = QtWidgets.QPushButton(self.layoutWidget2)
        self.Button_submit.setObjectName("Button_submit")
        self.horizontalLayout_6.addWidget(self.Button_submit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.layoutWidget2)
        self.plainTextEdit_2.setToolTip("")
        self.plainTextEdit_2.setToolTipDuration(2)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout_2.addWidget(self.plainTextEdit_2)
        self.step_tabs.addTab(self.query_tab, "")
        self.convert_tab = QtWidgets.QWidget()
        self.convert_tab.setObjectName("convert_tab")
        self.format_tabs = QtWidgets.QTabWidget(self.convert_tab)
        self.format_tabs.setGeometry(QtCore.QRect(10, 50, 831, 451))
        self.format_tabs.setObjectName("format_tabs")
        self.speck_tab = QtWidgets.QWidget()
        self.speck_tab.setObjectName("speck_tab")
        self.gbox_color = QtWidgets.QGroupBox(self.speck_tab)
        self.gbox_color.setGeometry(QtCore.QRect(0, 240, 411, 171))
        self.gbox_color.setCheckable(True)
        self.gbox_color.setChecked(True)
        self.gbox_color.setObjectName("gbox_color")
        self.layoutWidget3 = QtWidgets.QWidget(self.gbox_color)
        self.layoutWidget3.setGeometry(QtCore.QRect(11, 31, 391, 131))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.formLayout_8 = QtWidgets.QFormLayout(self.layoutWidget3)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_8.setObjectName("label_8")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.cmb_gmean_mag = QtWidgets.QComboBox(self.layoutWidget3)
        self.cmb_gmean_mag.setObjectName("cmb_gmean_mag")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmb_gmean_mag)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_3.setObjectName("label_3")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cmb_bp_mean_mag = QtWidgets.QComboBox(self.layoutWidget3)
        self.cmb_bp_mean_mag.setObjectName("cmb_bp_mean_mag")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmb_bp_mean_mag)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_5.setObjectName("label_5")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.cmb_gaap = QtWidgets.QComboBox(self.layoutWidget3)
        self.cmb_gaap.setObjectName("cmb_gaap")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmb_gaap)
        self.gbox_mag = QtWidgets.QGroupBox(self.speck_tab)
        self.gbox_mag.setGeometry(QtCore.QRect(420, 240, 411, 171))
        self.gbox_mag.setCheckable(True)
        self.gbox_mag.setChecked(True)
        self.gbox_mag.setObjectName("gbox_mag")
        self.layoutWidget4 = QtWidgets.QWidget(self.gbox_mag)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 30, 391, 27))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.cmb_meanmag = QtWidgets.QComboBox(self.layoutWidget4)
        self.cmb_meanmag.setObjectName("cmb_meanmag")
        self.horizontalLayout_10.addWidget(self.cmb_meanmag)
        self.gbox_speed = QtWidgets.QGroupBox(self.speck_tab)
        self.gbox_speed.setGeometry(QtCore.QRect(420, 0, 411, 221))
        self.gbox_speed.setCheckable(True)
        self.gbox_speed.setChecked(True)
        self.gbox_speed.setObjectName("gbox_speed")
        self.layoutWidget5 = QtWidgets.QWidget(self.gbox_speed)
        self.layoutWidget5.setGeometry(QtCore.QRect(11, 31, 391, 182))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget5)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cmb_pmra = QtWidgets.QComboBox(self.layoutWidget5)
        self.cmb_pmra.setEnabled(True)
        self.cmb_pmra.setObjectName("cmb_pmra")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmb_pmra)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.cmb_pmdec = QtWidgets.QComboBox(self.layoutWidget5)
        self.cmb_pmdec.setObjectName("cmb_pmdec")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmb_pmdec)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.cmb_rv = QtWidgets.QComboBox(self.layoutWidget5)
        self.cmb_rv.setObjectName("cmb_rv")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmb_rv)
        self.gbox_xyz = QtWidgets.QGroupBox(self.speck_tab)
        self.gbox_xyz.setGeometry(QtCore.QRect(0, 0, 411, 221))
        self.gbox_xyz.setCheckable(True)
        self.gbox_xyz.setChecked(True)
        self.gbox_xyz.setObjectName("gbox_xyz")
        self.layoutWidget6 = QtWidgets.QWidget(self.gbox_xyz)
        self.layoutWidget6.setGeometry(QtCore.QRect(14, 34, 391, 89))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget6)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.raw_lbl = QtWidgets.QLabel(self.layoutWidget6)
        self.raw_lbl.setObjectName("raw_lbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.raw_lbl)
        self.cmb_ra = QtWidgets.QComboBox(self.layoutWidget6)
        self.cmb_ra.setEnabled(True)
        self.cmb_ra.setObjectName("cmb_ra")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmb_ra)
        self.dec_lbl = QtWidgets.QLabel(self.layoutWidget6)
        self.dec_lbl.setObjectName("dec_lbl")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dec_lbl)
        self.cmb_dec = QtWidgets.QComboBox(self.layoutWidget6)
        self.cmb_dec.setObjectName("cmb_dec")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmb_dec)
        self.cmb_dist_par = QtWidgets.QComboBox(self.layoutWidget6)
        self.cmb_dist_par.setObjectName("cmb_dist_par")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cmb_dist_par)
        self.cmb_rs_par = QtWidgets.QComboBox(self.layoutWidget6)
        self.cmb_rs_par.setObjectName("cmb_rs_par")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmb_rs_par)
        self.format_tabs.addTab(self.speck_tab, "")
        self.sfits_tab = QtWidgets.QWidget()
        self.sfits_tab.setObjectName("sfits_tab")
        self.gbox_speed_sf = QtWidgets.QGroupBox(self.sfits_tab)
        self.gbox_speed_sf.setGeometry(QtCore.QRect(420, 0, 411, 221))
        self.gbox_speed_sf.setCheckable(True)
        self.gbox_speed_sf.setChecked(True)
        self.gbox_speed_sf.setObjectName("gbox_speed_sf")
        self.layoutWidget_2 = QtWidgets.QWidget(self.gbox_speed_sf)
        self.layoutWidget_2.setGeometry(QtCore.QRect(11, 31, 391, 182))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.cmb_pmra_2 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.cmb_pmra_2.setObjectName("cmb_pmra_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmb_pmra_2)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.cmb_pmdec_2 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.cmb_pmdec_2.setObjectName("cmb_pmdec_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmb_pmdec_2)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.cmb_rv_2 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.cmb_rv_2.setObjectName("cmb_rv_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmb_rv_2)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.cmb_pmra_err_2 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.cmb_pmra_err_2.setObjectName("cmb_pmra_err_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cmb_pmra_err_2)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.cmb_pmdec_err_2 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.cmb_pmdec_err_2.setObjectName("cmb_pmdec_err_2")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cmb_pmdec_err_2)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.cmb_rdvel_err_2 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.cmb_rdvel_err_2.setObjectName("cmb_rdvel_err_2")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cmb_rdvel_err_2)
        self.gbox_xyz_sf = QtWidgets.QGroupBox(self.sfits_tab)
        self.gbox_xyz_sf.setGeometry(QtCore.QRect(0, 0, 411, 221))
        self.gbox_xyz_sf.setCheckable(True)
        self.gbox_xyz_sf.setChecked(True)
        self.gbox_xyz_sf.setObjectName("gbox_xyz_sf")
        self.layoutWidget_3 = QtWidgets.QWidget(self.gbox_xyz_sf)
        self.layoutWidget_3.setGeometry(QtCore.QRect(12, 32, 391, 182))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.layoutWidget_3)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.raw_lbl_2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.raw_lbl_2.setObjectName("raw_lbl_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.raw_lbl_2)
        self.cmb_ra_2 = QtWidgets.QComboBox(self.layoutWidget_3)
        self.cmb_ra_2.setEnabled(True)
        self.cmb_ra_2.setObjectName("cmb_ra_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmb_ra_2)
        self.dec_lbl_2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.dec_lbl_2.setObjectName("dec_lbl_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dec_lbl_2)
        self.cmb_dec_2 = QtWidgets.QComboBox(self.layoutWidget_3)
        self.cmb_dec_2.setObjectName("cmb_dec_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmb_dec_2)
        self.cmb_dist_par_2 = QtWidgets.QComboBox(self.layoutWidget_3)
        self.cmb_dist_par_2.setObjectName("cmb_dist_par_2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cmb_dist_par_2)
        self.cmb_rs_par_2 = QtWidgets.QComboBox(self.layoutWidget_3)
        self.cmb_rs_par_2.setObjectName("cmb_rs_par_2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmb_rs_par_2)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_29.setObjectName("label_29")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.cmb_plx_err_2 = QtWidgets.QComboBox(self.layoutWidget_3)
        self.cmb_plx_err_2.setObjectName("cmb_plx_err_2")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cmb_plx_err_2)
        self.gbox_mag_sf = QtWidgets.QGroupBox(self.sfits_tab)
        self.gbox_mag_sf.setGeometry(QtCore.QRect(420, 230, 411, 181))
        self.gbox_mag_sf.setCheckable(True)
        self.gbox_mag_sf.setChecked(True)
        self.gbox_mag_sf.setObjectName("gbox_mag_sf")
        self.layoutWidget7 = QtWidgets.QWidget(self.gbox_mag_sf)
        self.layoutWidget7.setGeometry(QtCore.QRect(11, 20, 391, 151))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.formLayout_5 = QtWidgets.QFormLayout(self.layoutWidget7)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_27.setObjectName("label_27")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.cmb_meanmag_2 = QtWidgets.QComboBox(self.layoutWidget7)
        self.cmb_meanmag_2.setObjectName("cmb_meanmag_2")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmb_meanmag_2)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_28.setObjectName("label_28")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget7)
        self.comboBox_5.setObjectName("comboBox_5")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_5)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_30.setObjectName("label_30")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.comboBox_6 = QtWidgets.QComboBox(self.layoutWidget7)
        self.comboBox_6.setObjectName("comboBox_6")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_6)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_31.setObjectName("label_31")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget7)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_32.setObjectName("label_32")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget7)
        self.comboBox_4.setObjectName("comboBox_4")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        self.format_tabs.addTab(self.sfits_tab, "")
        self.mfits_tab = QtWidgets.QWidget()
        self.mfits_tab.setObjectName("mfits_tab")
        self.gbox_speed_mf = QtWidgets.QGroupBox(self.mfits_tab)
        self.gbox_speed_mf.setGeometry(QtCore.QRect(420, 0, 411, 221))
        self.gbox_speed_mf.setCheckable(True)
        self.gbox_speed_mf.setChecked(True)
        self.gbox_speed_mf.setObjectName("gbox_speed_mf")
        self.layoutWidget_4 = QtWidgets.QWidget(self.gbox_speed_mf)
        self.layoutWidget_4.setGeometry(QtCore.QRect(11, 31, 391, 182))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.formLayout_6 = QtWidgets.QFormLayout(self.layoutWidget_4)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_33.setObjectName("label_33")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.cmb_pmra_3 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.cmb_pmra_3.setObjectName("cmb_pmra_3")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmb_pmra_3)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_34.setObjectName("label_34")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.cmb_pmdec_3 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.cmb_pmdec_3.setObjectName("cmb_pmdec_3")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmb_pmdec_3)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_35.setObjectName("label_35")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.cmb_rv_3 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.cmb_rv_3.setObjectName("cmb_rv_3")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmb_rv_3)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_36.setObjectName("label_36")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.cmb_pmra_err_3 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.cmb_pmra_err_3.setObjectName("cmb_pmra_err_3")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cmb_pmra_err_3)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_37.setObjectName("label_37")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.cmb_pmdec_err_3 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.cmb_pmdec_err_3.setObjectName("cmb_pmdec_err_3")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cmb_pmdec_err_3)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_38.setObjectName("label_38")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.cmb_rdvel_err_3 = QtWidgets.QComboBox(self.layoutWidget_4)
        self.cmb_rdvel_err_3.setObjectName("cmb_rdvel_err_3")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cmb_rdvel_err_3)
        self.gbox_xyz_mf = QtWidgets.QGroupBox(self.mfits_tab)
        self.gbox_xyz_mf.setGeometry(QtCore.QRect(0, 0, 411, 221))
        self.gbox_xyz_mf.setCheckable(True)
        self.gbox_xyz_mf.setChecked(True)
        self.gbox_xyz_mf.setObjectName("gbox_xyz_mf")
        self.layoutWidget_5 = QtWidgets.QWidget(self.gbox_xyz_mf)
        self.layoutWidget_5.setGeometry(QtCore.QRect(12, 32, 391, 182))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.formLayout_7 = QtWidgets.QFormLayout(self.layoutWidget_5)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.raw_lbl_3 = QtWidgets.QLabel(self.layoutWidget_5)
        self.raw_lbl_3.setObjectName("raw_lbl_3")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.raw_lbl_3)
        self.cmb_ra_3 = QtWidgets.QComboBox(self.layoutWidget_5)
        self.cmb_ra_3.setEnabled(True)
        self.cmb_ra_3.setObjectName("cmb_ra_3")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmb_ra_3)
        self.dec_lbl_3 = QtWidgets.QLabel(self.layoutWidget_5)
        self.dec_lbl_3.setObjectName("dec_lbl_3")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dec_lbl_3)
        self.cmb_dec_3 = QtWidgets.QComboBox(self.layoutWidget_5)
        self.cmb_dec_3.setObjectName("cmb_dec_3")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmb_dec_3)
        self.cmb_dist_par_3 = QtWidgets.QComboBox(self.layoutWidget_5)
        self.cmb_dist_par_3.setObjectName("cmb_dist_par_3")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cmb_dist_par_3)
        self.cmb_rs_par_3 = QtWidgets.QComboBox(self.layoutWidget_5)
        self.cmb_rs_par_3.setObjectName("cmb_rs_par_3")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmb_rs_par_3)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_39.setObjectName("label_39")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.cmb_ra_err_2 = QtWidgets.QComboBox(self.layoutWidget_5)
        self.cmb_ra_err_2.setObjectName("cmb_ra_err_2")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cmb_ra_err_2)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_40.setObjectName("label_40")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.cmb_dec_err_2 = QtWidgets.QComboBox(self.layoutWidget_5)
        self.cmb_dec_err_2.setObjectName("cmb_dec_err_2")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cmb_dec_err_2)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_41.setObjectName("label_41")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.cmb_plx_err_3 = QtWidgets.QComboBox(self.layoutWidget_5)
        self.cmb_plx_err_3.setObjectName("cmb_plx_err_3")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cmb_plx_err_3)
        self.gbox_color_mf = QtWidgets.QGroupBox(self.mfits_tab)
        self.gbox_color_mf.setGeometry(QtCore.QRect(0, 230, 411, 181))
        self.gbox_color_mf.setCheckable(True)
        self.gbox_color_mf.setChecked(True)
        self.gbox_color_mf.setObjectName("gbox_color_mf")
        self.layoutWidget8 = QtWidgets.QWidget(self.gbox_color_mf)
        self.layoutWidget8.setGeometry(QtCore.QRect(12, 40, 391, 89))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.formLayout_10 = QtWidgets.QFormLayout(self.layoutWidget8)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_42 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_42.setObjectName("label_42")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.cmb_gmean_mag_2 = QtWidgets.QComboBox(self.layoutWidget8)
        self.cmb_gmean_mag_2.setMinimumSize(QtCore.QSize(251, 0))
        self.cmb_gmean_mag_2.setObjectName("cmb_gmean_mag_2")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmb_gmean_mag_2)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_43.setObjectName("label_43")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_43)
        self.cmb_bp_mena_mag_2 = QtWidgets.QComboBox(self.layoutWidget8)
        self.cmb_bp_mena_mag_2.setMinimumSize(QtCore.QSize(251, 0))
        self.cmb_bp_mena_mag_2.setObjectName("cmb_bp_mena_mag_2")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmb_bp_mena_mag_2)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_45.setObjectName("label_45")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_45)
        self.comboBox_7 = QtWidgets.QComboBox(self.layoutWidget8)
        self.comboBox_7.setMinimumSize(QtCore.QSize(251, 0))
        self.comboBox_7.setObjectName("comboBox_7")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_7)
        self.gbox_bp_mf = QtWidgets.QGroupBox(self.mfits_tab)
        self.gbox_bp_mf.setGeometry(QtCore.QRect(420, 230, 401, 181))
        self.gbox_bp_mf.setTitle("")
        self.gbox_bp_mf.setCheckable(True)
        self.gbox_bp_mf.setChecked(True)
        self.gbox_bp_mf.setObjectName("gbox_bp_mf")
        self.layoutWidget9 = QtWidgets.QWidget(self.gbox_bp_mf)
        self.layoutWidget9.setGeometry(QtCore.QRect(8, 38, 391, 89))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.formLayout_9 = QtWidgets.QFormLayout(self.layoutWidget9)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_46 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_46.setObjectName("label_46")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.comboBox_8 = QtWidgets.QComboBox(self.layoutWidget9)
        self.comboBox_8.setMinimumSize(QtCore.QSize(251, 0))
        self.comboBox_8.setObjectName("comboBox_8")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_8)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_47.setObjectName("label_47")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.comboBox_9 = QtWidgets.QComboBox(self.layoutWidget9)
        self.comboBox_9.setMinimumSize(QtCore.QSize(251, 0))
        self.comboBox_9.setObjectName("comboBox_9")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_9)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_44.setObjectName("label_44")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_44)
        self.cmb_g_rp_2 = QtWidgets.QComboBox(self.layoutWidget9)
        self.cmb_g_rp_2.setMinimumSize(QtCore.QSize(251, 0))
        self.cmb_g_rp_2.setObjectName("cmb_g_rp_2")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmb_g_rp_2)
        self.format_tabs.addTab(self.mfits_tab, "")
        self.label_7 = QtWidgets.QLabel(self.convert_tab)
        self.label_7.setGeometry(QtCore.QRect(400, 540, 101, 17))
        self.label_7.setObjectName("label_7")
        self.buttonGetFilename = QtWidgets.QPushButton(self.convert_tab)
        self.buttonGetFilename.setGeometry(QtCore.QRect(180, 540, 121, 25))
        self.buttonGetFilename.setObjectName("buttonGetFilename")
        self.layoutWidget10 = QtWidgets.QWidget(self.convert_tab)
        self.layoutWidget10.setGeometry(QtCore.QRect(13, 11, 831, 27))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_8.addWidget(self.label_18)
        self.lEdit_src_name = QtWidgets.QLineEdit(self.layoutWidget10)
        self.lEdit_src_name.setMinimumSize(QtCore.QSize(150, 0))
        self.lEdit_src_name.setText("")
        self.lEdit_src_name.setObjectName("lEdit_src_name")
        self.horizontalLayout_8.addWidget(self.lEdit_src_name)
        self.buttonSelectFile = QtWidgets.QPushButton(self.layoutWidget10)
        self.buttonSelectFile.setMaximumSize(QtCore.QSize(30, 16777215))
        self.buttonSelectFile.setObjectName("buttonSelectFile")
        self.horizontalLayout_8.addWidget(self.buttonSelectFile)
        self.lbl_ds = QtWidgets.QLabel(self.layoutWidget10)
        self.lbl_ds.setObjectName("lbl_ds")
        self.horizontalLayout_8.addWidget(self.lbl_ds)
        self.le_data_source = QtWidgets.QLineEdit(self.layoutWidget10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_data_source.sizePolicy().hasHeightForWidth())
        self.le_data_source.setSizePolicy(sizePolicy)
        self.le_data_source.setMinimumSize(QtCore.QSize(40, 0))
        self.le_data_source.setMaximumSize(QtCore.QSize(100, 16777211))
        self.le_data_source.setBaseSize(QtCore.QSize(0, 0))
        self.le_data_source.setObjectName("le_data_source")
        self.horizontalLayout_8.addWidget(self.le_data_source)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_8.addWidget(self.label_21)
        self.le_table = QtWidgets.QLineEdit(self.layoutWidget10)
        self.le_table.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_table.setObjectName("le_table")
        self.horizontalLayout_8.addWidget(self.le_table)
        self.label_output_desc = QtWidgets.QLabel(self.convert_tab)
        self.label_output_desc.setGeometry(QtCore.QRect(26, 510, 81, 20))
        self.label_output_desc.setObjectName("label_output_desc")
        self.lE_output_desc = QtWidgets.QLineEdit(self.convert_tab)
        self.lE_output_desc.setGeometry(QtCore.QRect(110, 510, 731, 25))
        self.lE_output_desc.setObjectName("lE_output_desc")
        self.comboBox_results = QtWidgets.QComboBox(self.convert_tab)
        self.comboBox_results.setGeometry(QtCore.QRect(460, 540, 381, 25))
        self.comboBox_results.setObjectName("comboBox_results")
        self.step_tabs.addTab(self.convert_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 864, 20))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuJob = QtWidgets.QMenu(self.menubar)
        self.menuJob.setObjectName("menuJob")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuJob.menuAction())

        self.retranslateUi(MainWindow)
        self.step_tabs.setCurrentIndex(0)
        self.format_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DomeCat"))
        self.label_data_source.setText(_translate("MainWindow", "Data source:"))
        self.label_tables.setText(_translate("MainWindow", "Tables:"))
        self.label.setText(_translate("MainWindow", "Selected tables:"))
        self.label_s_desc.setText(_translate("MainWindow", "Query description"))
        self.label_4.setText(_translate("MainWindow", "Template"))
        self.label_conditions.setText(_translate("MainWindow", "Selected columns"))
        self.label_2.setText(_translate("MainWindow", "Conditions across tables"))
        self.Button_add_cond.setText(_translate("MainWindow", "Add"))
        self.cmb_cross_ops.setCurrentText(_translate("MainWindow", "="))
        self.cmb_cross_ops.setItemText(0, _translate("MainWindow", "="))
        self.cmb_cross_ops.setItemText(1, _translate("MainWindow", ">="))
        self.cmb_cross_ops.setItemText(2, _translate("MainWindow", "<="))
        self.cmb_cross_ops.setItemText(3, _translate("MainWindow", "<>"))
        self.ButtonADQL.setText(_translate("MainWindow", "ADQL"))
        self.label_19.setText(_translate("MainWindow", "File name:"))
        self.Button_submit.setText(_translate("MainWindow", "Save"))
        self.step_tabs.setTabText(self.step_tabs.indexOf(self.query_tab), _translate("MainWindow", "Query"))
        self.gbox_color.setTitle(_translate("MainWindow", "COLOR  "))
        self.label_8.setText(_translate("MainWindow", "MAG (Lo freq)"))
        self.label_3.setText(_translate("MainWindow", "MAG (Hi Freq)"))
        self.label_5.setText(_translate("MainWindow", "Color"))
        self.gbox_mag.setTitle(_translate("MainWindow", "ABSOLUTE MAGNITUDE"))
        self.label_17.setText(_translate("MainWindow", "Absolute Magnitude"))
        self.gbox_speed.setTitle(_translate("MainWindow", "VX, VY, VZ, SPEED"))
        self.label_13.setText(_translate("MainWindow", "RA-VELOCITY"))
        self.label_14.setText(_translate("MainWindow", "DEC-VELOCITY"))
        self.label_15.setText(_translate("MainWindow", "RADIAL _VELOCITY"))
        self.gbox_xyz.setTitle(_translate("MainWindow", "x, y, z"))
        self.raw_lbl.setText(_translate("MainWindow", "RA"))
        self.dec_lbl.setText(_translate("MainWindow", "DEC"))
        self.format_tabs.setTabText(self.format_tabs.indexOf(self.speck_tab), _translate("MainWindow", "Speck"))
        self.gbox_speed_sf.setTitle(_translate("MainWindow", "VX, VY, VZ, SPEED"))
        self.label_16.setText(_translate("MainWindow", "PMRA"))
        self.label_22.setText(_translate("MainWindow", "PMDEC"))
        self.label_23.setText(_translate("MainWindow", "RADIAL _VELOCITY"))
        self.label_24.setText(_translate("MainWindow", "PMRA_ERR"))
        self.label_25.setText(_translate("MainWindow", "PMDEC_ERR"))
        self.label_26.setText(_translate("MainWindow", "RD_VEL_ERR"))
        self.gbox_xyz_sf.setTitle(_translate("MainWindow", "x, y, z                           column    "))
        self.raw_lbl_2.setText(_translate("MainWindow", "RA"))
        self.dec_lbl_2.setText(_translate("MainWindow", "DEC"))
        self.label_29.setText(_translate("MainWindow", "PLX_ERR"))
        self.gbox_mag_sf.setTitle(_translate("MainWindow", "MAGNITUDES"))
        self.label_27.setText(_translate("MainWindow", "G MAG"))
        self.label_28.setText(_translate("MainWindow", "TYCHO_B_MAG"))
        self.label_30.setText(_translate("MainWindow", "TYCHO_V_MAG"))
        self.label_31.setText(_translate("MainWindow", "TYCHO_B_MAG_ERR"))
        self.label_32.setText(_translate("MainWindow", "TYCHO_V_MAG_ERR"))
        self.format_tabs.setTabText(self.format_tabs.indexOf(self.sfits_tab), _translate("MainWindow", "Single fits"))
        self.gbox_speed_mf.setTitle(_translate("MainWindow", "VX, VY, VZ, SPEED"))
        self.label_33.setText(_translate("MainWindow", "PMRA"))
        self.label_34.setText(_translate("MainWindow", "PMDEC"))
        self.label_35.setText(_translate("MainWindow", "RADIAL _VELOCITY"))
        self.label_36.setText(_translate("MainWindow", "PMRA_ERR"))
        self.label_37.setText(_translate("MainWindow", "PMDEC_ERR"))
        self.label_38.setText(_translate("MainWindow", "RD_VEL_ERR"))
        self.gbox_xyz_mf.setTitle(_translate("MainWindow", "x, y, z                           column    "))
        self.raw_lbl_3.setText(_translate("MainWindow", "RA"))
        self.dec_lbl_3.setText(_translate("MainWindow", "DEC"))
        self.label_39.setText(_translate("MainWindow", "RA_ERR"))
        self.label_40.setText(_translate("MainWindow", "DEC_ERR"))
        self.label_41.setText(_translate("MainWindow", "PLX_ERR"))
        self.gbox_color_mf.setTitle(_translate("MainWindow", "COLOR  "))
        self.label_42.setText(_translate("MainWindow", "G_MEAN_MAG"))
        self.label_43.setText(_translate("MainWindow", "BP_MEAN_MAG"))
        self.label_45.setText(_translate("MainWindow", "RP_MEAN_MAG"))
        self.label_46.setText(_translate("MainWindow", "BP_RP"))
        self.label_47.setText(_translate("MainWindow", "BP_GP"))
        self.label_44.setText(_translate("MainWindow", "G_RP"))
        self.format_tabs.setTabText(self.format_tabs.indexOf(self.mfits_tab), _translate("MainWindow", "Multiple fits"))
        self.label_7.setText(_translate("MainWindow", "Results"))
        self.buttonGetFilename.setText(_translate("MainWindow", "Convert/save"))
        self.label_18.setText(_translate("MainWindow", "Source file:"))
        self.buttonSelectFile.setText(_translate("MainWindow", "..."))
        self.lbl_ds.setText(_translate("MainWindow", "Data source:"))
        self.label_21.setText(_translate("MainWindow", "Table:"))
        self.label_output_desc.setText(_translate("MainWindow", "Description"))
        self.step_tabs.setTabText(self.step_tabs.indexOf(self.convert_tab), _translate("MainWindow", "Convert"))
        self.menuJob.setTitle(_translate("MainWindow", "Job"))

